site_name: Computational Physics

extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni

theme:
  name: 'material'
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

extra_css:
  - extra.css

extra:
  analytics:
    provider: google
    property: UA-156178967-1



nav:
- Home: index.md
- Introduction to Statistical Mechanics: introduction_to_statistical_mechanics.md
- Classical Statistical Mechanics: classical_statistical_mechanics.md
- Quantum Statistical Mechanics: quantum_statistical_mechanics.md
- The Canonical Ensemble: the_canonical_ensemble.md
- The Grand Canonical Ensemble: the_grand_canonical_ensemble.md
- Microcanonical Ensemble: microcanonical_ensemble.md
- Phase Transitions and Critical Phenomena: phase_transitions_and_critical_phenomena.md
- The Ising Model 1D: the_ising_model_1d.md
- The Ising Model 2D: the_ising_model_2d.md
- The Ising Model 3D: the_ising_model_3d.md
- The XY Model: the_xy_model.md
- The Heisenberg Model: the_heisenberg_model.md
- The Potts Model: the_potts_model.md
- The q-state Potts Model: the_q_state_potts_model.md
- The Blume-Capel Model: the_blume_capel_model.md
- The Ashkin-Teller Model: the_ashkin_teller_model.md
- The Clock Model: the_clock_model.md
- The Percolation Model: the_percolation_model.md
- Spin Glasses: spin_glasses.md
- Lattice Gas Models: lattice_gas_models.md
- Cellular Automata Models: cellular_automata_models.md
- Hard Sphere Models: hard_sphere_models.md
- Soft Sphere Models: soft_sphere_models.md
- Lennard-Jones Potential Models: lennard_jones_potential_models.md
- The Ideal Gas Model: the_ideal_gas_model.md
- The Van der Waals Gas Model: the_van_der_waals_gas_model.md
- Real Gas Models: real_gas_models.md
- The Bose-Einstein Condensate: the_bose_einstein_condensate.md
- The Fermion System: the_fermion_system.md
- The Boson System: the_boson_system.md
- The Many-body System: the_many_body_system.md
- Quantum Monte Carlo Methods: quantum_monte_carlo_methods.md
- Classical Monte Carlo Methods: classical_monte_carlo_methods.md
- Path Integral Monte Carlo: path_integral_monte_carlo.md
- Replica Monte Carlo: replica_monte_carlo.md
- Cluster Algorithms: cluster_algorithms.md
- Metropolis-Hastings Algorithm: metropolis_hastings_algorithm.md
- Heat Bath Algorithm: heat_bath_algorithm.md
- Wang-Landau Algorithm: wang_landau_algorithm.md
- Multicanonical Ensemble: multicanonical_ensemble.md
- Quantum Spin Models: quantum_spin_models.md
- Hubbard Model: hubbard_model.md
- t-J Model: t_j_model.md
- The Anderson Model: the_anderson_model.md
- Density Functional Theory: density_functional_theory.md
- Quantum Lattice Models: quantum_lattice_models.md
- Lattice Gauge Theory: lattice_gauge_theory.md
- Molecular Dynamics Simulations: molecular_dynamics_simulations.md
- Langevin Dynamics: langevin_dynamics.md
- Brownian Motion: brownian_motion.md
- Non-equilibrium Statistical Mechanics: non_equilibrium_statistical_mechanics.md
- Renormalization Group Theory: renormalization_group_theory.md
- Mean Field Theory: mean_field_theory.md
- Finite Size Scaling: finite_size_scaling.md
- Quantum Phase Transitions: quantum_phase_transitions.md
- Topological Phases of Matter: topological_phases_of_matter.md
- Frustrated Systems: frustrated_systems.md
- Quantum Magnetism: quantum_magnetism.md
- High-temperature Superconductors: high_temperature_superconductors.md
- Quantum Hall Effect: quantum_hall_effect.md
- Anderson Localization: anderson_localization.md
- Quantum Monte Carlo in Condensed Matter: quantum_monte_carlo_in_condensed_matter.md
- Quantum Dots and Wires: quantum_dots_and_wires.md
- Spintronics: spintronics.md
- Nonequilibrium Green’s Functions: nonequilibrium_greens_functions.md
- Monte Carlo Methods for Lattice Field Theory: monte_carlo_methods_for_lattice_field_theory.md
- Quantum Monte Carlo for Bosonic Systems: quantum_monte_carlo_for_bosonic_systems.md
- Quantum Monte Carlo for Fermionic Systems: quantum_monte_carlo_for_fermionic_systems.md


